table 'Product Categories Lookup'
	excludeFromModelRefresh
	lineageTag: b1c0cf1f-2997-4323-b4c2-010d0483b474

	column ProductCategoryKey
		dataType: int64
		formatString: 0
		lineageTag: 64622020-f4e0-4a98-8fa3-40933d95a928
		summarizeBy: none
		sourceColumn: ProductCategoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CategoryName
		dataType: string
		lineageTag: c4a253d2-d998-4da5-afcd-46ac27437a79
		summarizeBy: none
		sourceColumn: CategoryName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Product Categories Lookup' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Krishna Kavthekar\Downloads\AdventureWorks+Raw+Data\AdventureWorks Raw Data\AdventureWorks Product Categories Lookup.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductCategoryKey", Int64.Type}, {"CategoryName", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

