table 'Territory Lookup'
	excludeFromModelRefresh
	lineageTag: 4ed82731-7ed8-4a33-8cae-1aec8ec0c408

	column SalesTerritoryKey
		dataType: int64
		isKey
		formatString: 0
		lineageTag: b1f165cd-039b-4010-875e-d718f26b6e69
		summarizeBy: none
		sourceColumn: SalesTerritoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: d9bc6aea-ab89-488f-9f55-64dc6749a816
		summarizeBy: none
		sourceColumn: Region

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: b27801cf-5607-4a55-ae30-28ceb34315fa
		dataCategory: Country
		summarizeBy: none
		sourceColumn: Country

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Continent
		dataType: string
		lineageTag: cbd0ebb2-6a83-48e7-96bf-7df2ce2a32ef
		dataCategory: Continent
		summarizeBy: none
		sourceColumn: Continent

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Territory Lookup' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Krishna Kavthekar\Downloads\AdventureWorks+Raw+Data\AdventureWorks Raw Data\AdventureWorks Territory Lookup.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"SalesTerritoryKey", Int64.Type}, {"Region", type text}, {"Country", type text}, {"Continent", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

